name: Deploy Examples
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      CLIENT_URL: /openeo-vue-components/
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build-examples
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: assets
          user_name: 'openEO CI'
          user_email: openeo.ci@uni-muenster.de